version: 2.1

orbs:
  slack: circleci/slack@4.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: apk add --no-cache curl jq
      - slack/notify:
          event: always
          custom: |
            {
              "text": "Triggering CICD",
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Triggering automatic deploy*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
